packages/frontend/components/ui/SearchTextInput.tsx

feat: dynamaic autocomplete

---

packages/frontend/features/results/sections/TitleSection.tsx

- 동적으로 klaci code 원형을 수정하도록 했습니다.

feat: dynamic klaci circles

---

packages/backend/src/auth/auth.controller.ts
packages/frontend/api/client.ts
packages/frontend/api/constants/endpoints.ts
packages/frontend/api/hooks/index.ts
packages/frontend/api/hooks/useAuth.ts
packages/frontend/api/hooks/useDistrict.ts
packages/frontend/api/services/auth.service.ts
packages/frontend/api/services/data.service.ts
packages/frontend/api/services/district.service.ts
packages/frontend/api/services/index.ts
packages/frontend/api/types/api.types.ts
packages/frontend/api/utils/errorHandler.ts
packages/frontend/package.json
packages/frontend/store/slices/authSlice.ts
yarn.lock

feat: api setup

---

packages/backend/src/auth/auth.controller.ts
packages/backend/src/auth/auth.service.ts
packages/backend/src/data/data.service.ts
packages/backend/src/data/types/region.types.ts
packages/frontend/api/services/data.service.ts
packages/frontend/store/types/district.ts

- DB 형태를 바꾸면서 그에 맞추어 쿼리와 타입을 변경했습니다.

feat: getRegion, getRegions 응답형태 수정

---

packages/backend/src/data/data.service.ts
packages/backend/src/data/types/region.types.ts
packages/frontend/api/services/data.service.ts
packages/frontend/features/results/sections/SummarySection.tsx
packages/frontend/features/results/sections/TitleSection.tsx
packages/frontend/store/types/district.ts

feat: data application into title, summary section

---

.github/workflows/deploy-develop.yml
packages/backend/src/main.ts

feat: cors setup + github workflow

---

packages/backend/src/data/data.service.ts
packages/backend/src/data/types/region.types.ts
packages/frontend/api/services/data.service.ts
packages/frontend/components/ui/CategoryDetailModal.tsx
packages/frontend/constants/colors.ts
packages/frontend/constants/data.ts
packages/frontend/features/results/components/CategoryRanking.tsx
packages/frontend/features/results/sections/CategoryRankingSection.tsx
packages/frontend/store/types/district.ts

- category rank 관련 fe/be 코드 업데이트

feat: actual category rank

---

packages/frontend/app/results/page.tsx

- set default region as regionid 1 (종로구)

feat: set default region

---

packages/backend/src/data/data.service.ts
packages/backend/src/data/types/region.types.ts
packages/frontend/api/client.ts
packages/frontend/api/hooks/useKeyIndexRanks.ts
packages/frontend/app/globals.css
packages/frontend/components/atoms/modal/IndexModal.tsx
packages/frontend/components/ui/IndexModal.tsx
packages/frontend/features/results/sections/StrenthWeaknessIndexSection.tsx
packages/frontend/store/types/district.ts
packages/frontend/types/common.ts

[feat: apply real data to indexmodal](https://github.com/powellstreet/k-laci/commit/53214e53b6d34dd1cbc872d4cd3bd253068a964d)
@[triplelight-dev](https://github.com/powellstreet/k-laci/commits?author=triplelight-dev)
triplelight-dev committed 49 minutes ago
[feat: add key index desc and apply it to modal](https://github.com/powellstreet/k-laci/commit/d63cbafc5924aa0b8cd1a0c74de8236fadbbe2cf)
@[triplelight-dev](https://github.com/powellstreet/k-laci/commits?author=triplelight-dev)
triplelight-dev committed 12 minutes ago
[feat: modal desc update](https://github.com/powellstreet/k-laci/commit/52875159ebc6df284b3fdd3c9855227e6df3fff7)
@[triplelight-dev](https://github.com/powellstreet/k-laci/commits?author=triplelight-dev)
triplelight-dev committed 5 minutes ago
[feat: modal cursor …

feat: feature updates

---

packages/backend/package.json
packages/backend/src/auth/auth.controller.ts
packages/backend/src/auth/auth.module.ts
packages/backend/src/auth/auth.service.ts
packages/backend/src/auth/dto/sign-up.dto.ts
packages/backend/src/auth/dto/verification-code.dto.ts
packages/backend/src/auth/email.service.ts
packages/backend/src/auth/verification-code.service.ts
packages/frontend/api/constants/endpoints.ts
packages/frontend/api/hooks/useAuth.ts
packages/frontend/api/services/auth.service.ts
packages/frontend/api/types/api.types.ts
packages/frontend/app/auth/signup/page.tsx
packages/frontend/app/auth/signup/profile/page.tsx
packages/frontend/components/MobileDetector.tsx
yarn.lock

- email verification with nodemailer & gmail
- change method from email verification to code verification

feat: email verification 

---

packages/frontend/components/atoms/charts/RadarBackground.tsx
packages/frontend/features/results/sections/CompetencyDistSection.tsx
packages/frontend/features/results/sections/TitleSection.tsx

feat: jewel chart update

---

packages/backend/src/data/data.service.ts
packages/backend/src/data/types/region.types.ts
packages/frontend/api/services/data.service.ts
packages/frontend/components/atoms/select/InterestRegionSelect.tsx
packages/frontend/features/results/sections/CompetencyDistSection.tsx
packages/frontend/features/results/sections/DistrictSelectSection.tsx
packages/frontend/features/results/sections/StrenthWeaknessIndexSection.tsx
packages/frontend/features/results/sections/TitleSection.tsx
packages/frontend/store/types/district.ts

feat: result update

---

packages/frontend/app/page.tsx
packages/frontend/features/home/sections/VideoSection.tsx

feat: home video

---

packages/backend/src/app.module.ts
packages/backend/src/auth/auth.controller.ts
packages/backend/src/auth/auth.module.ts
packages/backend/src/auth/auth.service.ts
packages/backend/src/main.ts
packages/frontend/api/client.ts
packages/frontend/api/services/logs.service.ts
packages/frontend/app/results/ResultsPageClient.tsx
packages/frontend/components/ui/SearchTextInput.tsx
packages/frontend/features/results/sections/DistrictSelectSection.tsx
packages/frontend/features/results/sections/TitleSection.tsx
packages/frontend/store/slices/districtSlice.ts
packages/frontend/utils/jwtUtils.ts
packages/frontend/utils/regionChangeLogger.ts

feat: logs

---

packages/frontend/features/home/components/RankCardSlider.tsx

fix : delete unused state

---

packages/backend/src/app.module.ts
packages/backend/src/main.ts
packages/backend/src/stats/dto/get-total-region-ranks.dto.ts
packages/backend/src/stats/dto/total-region-rank-response.dto.ts
packages/backend/src/stats/stats.controller.ts
packages/backend/src/stats/stats.module.ts
packages/backend/src/stats/stats.service.ts
packages/frontend/api/constants/endpoints.ts
packages/frontend/api/hooks/index.ts
packages/frontend/api/hooks/useTotalRegionRanks.ts
packages/frontend/api/services/index.ts
packages/frontend/api/services/stats.service.ts
packages/frontend/api/types/stats.types.ts
packages/frontend/app/summary/layout.tsx
packages/frontend/app/summary/page.tsx
packages/frontend/app/summary/top-100/Top100PageClient.tsx
packages/frontend/app/summary/top-100/page.tsx
packages/frontend/components/layout/SummaryLayout.tsx
packages/frontend/components/sections/TotalRankingSection.tsx

- 서머리 페이지에 종합랭킹 100 을 우선 추가했습니다.

feat: summary top 100

---

packages/backend/src/stats/stats.service.ts
packages/frontend/app/results/ResultsPageClient.tsx
packages/frontend/features/results/sections/StrenthWeaknessIndexSection.tsx

- 강약점 소팅 에러
- 서머리에서 페이지 이동 우선순위 에러
- 강약점 텍스트 분기
에러를 수정했습니다.

fix: error fixes

---

.github/workflows/deploy-develop.yml

fix: deploy yml

---

packages/frontend/components/atoms/circle/KlaciCodeCircles.tsx
packages/frontend/components/ui/RankingTable.tsx
packages/frontend/public/sitemap-0.xml

hotfix: build error fix

---

packages/frontend/features/auth/components/ResetPasswordForm.tsx

chores: input color change

---

packages/backend/src/auth/dto/complete-signup.dto.ts
packages/backend/src/auth/dto/sign-up.dto.ts
packages/backend/src/auth/types/auth.types.ts
packages/frontend/api/services/auth.service.ts
packages/frontend/api/types/user.types.ts
packages/frontend/app/auth/signup/SignupPageClient.tsx
packages/frontend/components/atoms/EmailDisplayBox.tsx
packages/frontend/components/atoms/UserTypeBadge.tsx
packages/frontend/features/signup/components/EmailVerificationForm.tsx
packages/frontend/features/signup/components/ProfileForm.tsx
packages/frontend/features/signup/hooks/useSignupFlow.ts
packages/frontend/features/signup/sections/ProfileSection.tsx
packages/frontend/utils/userTypeUtils.ts

- set usertype edu into business
- constantize usertype

chores: set user type
